#!/usr/bin/env ruby
# kampa
#
# Command line activity file uploader

=begin
---
strava:
  access_token: xxxxx
garmin:
  username: xxxxx
  password: xxxxx
=end

require 'json'
require 'yaml'

# Load service files
Dir[File.join(__dir__, 'services', '*.rb')].each do |service|
  require service
end

class Kampa
  include Services

  def initialize
    # Load user configuration file
    conf_file = "#{Dir.home}/.config/kampa/conf.yml"
    if File.exist? conf_file
      @services = YAML::load_file conf_file
    else
      puts "Place access information in #{conf_file}"
      exit 1
    end
  end

  def upload(*files)
    # Make sure files exist
    files.each do |f|
      if not File.readable?(f)
        STDERR.puts "Unable to open #{f} for reading. Aborting."
        exit 2
      end
    end

    # Upload to each service
    @services.each do |service, conf|
      begin
        puts "Uploading to #{service}..."

        send("upload_to_#{service}", files, conf)

        puts "Finished uploading to #{service}."
      rescue => ex
        puts ex

        # Skip if errors occur
        STDERR.puts "Unable to upload to #{service}, skipping."
      end
    end
  end
end

if ARGV.length < 1
  puts "Usage: #$0 [activity-file] ..."
  puts "Upload activities to various services"

  exit 0
end

Kampa.new.upload(*ARGV)

# vim: set ft=ruby
